#!/bin/sh

set -e

ARCHITECTURES_VALUE="${PHOENIX_LIVE_ARCHITECTURE:-amd64}"
LINUX_FLAVOUR_VALUE="${PHOENIX_LIVE_LINUX_FLAVOUR:-amd64}"
BOOTLOADER_VALUE="${PHOENIX_LIVE_BOOTLOADER:-grub-efi}"

lb config noauto \
    --mode debian \
    --system live \
    --architectures "$ARCHITECTURES_VALUE" \
    --linux-flavours "$LINUX_FLAVOUR_VALUE" \
    --debian-installer false \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-indices false \
    --memtest none \
    --iso-application "Phoenix OS" \
    --iso-publisher "Phoenix OS Project" \
    --iso-volume "PHOENIX_OS" \
    --binary-images iso-hybrid \
    --chroot-filesystem squashfs \
    --compression xz \
    --zsync false \
    --bootappend-live "boot=live components quiet splash username=phoenix plymouth.ignore-serial-consoles console=tty0 console=ttyS0,115200n8 locales=en_US.UTF-8 keyboard-layouts=us" \
    --bootloader "$BOOTLOADER_VALUE" \
    "${@}"
