# Phoenix OS — Calamares: machineid module
# File: installer/calamares-config/modules/machineid.conf
---
# Generate new machine-id and dbus UUID for installed system
systemd:  true
dbus:     true
symlink:  true
