name: CI (Windows)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Support longpaths
        run: git config --global core.longpaths true
      - uses: actions/checkout@v4
        with:
          submodules: false

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --workspace

      - name: Test
        run: cargo test --workspace
